
default-resources:
  mem_mb: 1000
  cpus_per_task: 1
  runtime: 10

printshellcmds: True

sdm:
  - conda


set-threads:
  map_paf: 12
  map_sam: 4
  pileup: 4

set-resources:
  map_paf:
    mem_mb: 16000
  separate_target:
    mem_mb: 8000
  map_sam:
    mem_mb: 8000
  pileup:
    mem_mb: 8000


groups:
  - record_unblocks=UNBLOCK
  - separate_target=SEPARATE

group-components:
  - UNBLOCK=100
  - SEPARATE=10

