
default-resources:
  mem_mb: 1000
  cpus_per_task: 1
  runtime: 10

printshellcmds: True

sdm:
  - conda


set-threads:
  map_paf: 4
  map_sam: 4
  pileup: 4


groups:
  - record_unblocks=UNBLOCK
  - separate_target=SEPARATE

group-components:
  - UNBLOCK=100
  - SEPARATE=10

